spring.application.name=ProyectoPrueba
server.port=5432

# Conexión a SQL Server (Apuntando a SQLEXPRESS)
spring.datasource.url=jdbc:postgresql://dpg-d6j2o4ea2pns7393hpcg-a.virginia-postgres.render.com/escuela_8axw
spring.datasource.username=escuela_8axw_user
spring.datasource.password=OiV2qwUmewzWkpVAtFzksUz5aMTdNqXa
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect